name: CI

on:
  push:
    branches:
    - master
    - release/*
  pull_request:
    branches:
    - master

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x
    - name: Build Release
      run: dotnet build --configuration Release
    - name: Test Release
      run: dotnet test --configuration Release
